dist: bionic
sudo: false
language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libgl1-mesa-dev

env:
  -CC=gcc-8
  -CXX=g++-8

install:
  - pip install --user conan cmake

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . -- -j2
  - ctest -j2