macro(ENSURE_OUT_OF_SOURCE_BUILD MSG)
    string(COMPARE EQUAL "${CMAKE_SOURCE_DIR}" "${CMAKE_BINARY_DIR}" insource)
    get_filename_component(PARENTDIR ${CMAKE_SOURCE_DIR} PATH)
    string(COMPARE EQUAL "${CMAKE_SOURCE_DIR}" "${PARENTDIR}" insourcesubdir)
    IF(insource OR insourcesubdir)
        message(FATAL_ERROR "${MSG}")
    ENDIF(insource OR insourcesubdir)
endmacro(ENSURE_OUT_OF_SOURCE_BUILD)